### ISSUE TITLE
Deprecation of some functions in SciPy

### ISSUE THREAD

**Issue by LucaCerina** [aim-lab/Oximetry_Toolbox#5]
Hi,
recent versions of Scipy (1.5.0 onward) deprecated `median_absolute_deviation` and it's now `median_abs_deviation`.
The current version in the requirements is 1.4.1, which is 3 years old. It would be best to update it or to add a conditional import if we have reasons to support that version specifically.

Best

**Comment by jeremy-levy** [comment]
You are right, I have updated the requirements.
Thanks
